apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    uid: cassandra-uid # Add this UID
    access: proxy
    url: cassandra:9042
    jsonData:
      keyspace: analytics
      consistency: ONE
    isDefault: true
    editable: true
