apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  labels:
    app: schema-registry
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: registry
  selector:
    app: schema-registry
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-external-service
  labels:
    app: schema-registry
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    name: registry
  selector:
    app: schema-registry